import { newId, supabase } from "@/lib/supabaseClient";
const FLAG_KEY="supabase-data-migrated-v2";const COURSES_KEY="liquid-courses-v1";const NOTES_KEY="glass-notes-v1";const COLLECTIONS_KEY="glass-notes-collections-v1";const ENGINE_KEY="liquid-glass-engine-v1";const THEME_KEY="liquid-glass-theme-v1";const DISPLAY_NAME_KEY="liquid-glass-display-name-v1";
type LegacyCourse={id:string;name:string;description?:string;color?:string;createdAt?:number};type LegacyNote={id:string;title?:string;body?:string;favorite?:boolean;collectionId?:string|null;updatedAt?:number};type LegacyCollection={id:string;name:string};
function read<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw)as T:fallback}catch{return fallback}}
function scoped(key:string,userId:string){return `${key}:${userId}`}
export async function runLegacyMigrationOnce(userId:string):Promise<boolean>{if(typeof window==="undefined"||!userId)return false;const flag=scoped(FLAG_KEY,userId);try{if(localStorage.getItem(flag))return false}catch{return false}
let changed=false;try{const{count,error}=await supabase.from("courses").select("id",{count:"exact",head:true});if(error)throw error;const legacyCourses=read<LegacyCourse[]>(scoped(COURSES_KEY,userId),[]);const courses=Array.isArray(legacyCourses)?legacyCourses:[];
// Only import legacy rows when the account has no cloud courses. Every source note
// is given its original id as source_id when it is a UUID; retries are then safely
// deduplicated by the database unique index. Existing cloud rows are never deleted.
if(!count&&courses.length){for(const legacy of courses){const courseId=newId();const{error:ce}=await supabase.from("courses").insert({id:courseId,user_id:userId,name:legacy.name??"Untitled course",description:legacy.description??"",color:legacy.color??"sky",...(legacy.createdAt?{created_at:new Date(legacy.createdAt).toISOString()}: {})});if(ce){const{data:existing}=await supabase.from("courses").select("id").eq("user_id",userId).eq("name",legacy.name??"Untitled course").maybeSingle();if(!existing)throw ce;}
const collections=read<LegacyCollection[]>(scoped(COLLECTIONS_KEY,userId)+`:${legacy.id}`,[]);const collectionMap=new Map<string,string>();for(const c of(Array.isArray(collections)?collections:[])){if(!c||typeof c.name!=="string")continue;const id=newId();const{error}=await supabase.from("collections").insert({id,user_id:userId,course_id:courseId,name:c.name});if(error){const{data:existing}=await supabase.from("collections").select("id").eq("course_id",courseId).eq("name",c.name).maybeSingle();if(!existing)throw error;collectionMap.set(c.id,existing.id)}else collectionMap.set(c.id,id);}
const notes=read<LegacyNote[]>(scoped(NOTES_KEY,userId)+`:${legacy.id}`,[]);for(const n of(Array.isArray(notes)?notes:[])){if(!n||typeof n.id!=="string")continue;const sourceId=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(n.id)?n.id:null;const row={id:newId(),user_id:userId,course_id:courseId,collection_id:n.collectionId?(collectionMap.get(n.collectionId)??null):null,title:n.title??"Untitled note",body:n.body??"",favorite:Boolean(n.favorite),updated_at:new Date(n.updatedAt??Date.now()).toISOString(),source_id:sourceId};const{error}=await supabase.from("notes").insert(row);if(error&&sourceId){const{data:existing}=await supabase.from("notes").select("id").eq("user_id",userId).eq("source_id",sourceId).maybeSingle();if(!existing)throw error}else if(error)throw error;changed=true;}}
}else if(!count){const globalNotes=read<LegacyNote[]>(NOTES_KEY,[]);const globalCollections=read<LegacyCollection[]>(COLLECTIONS_KEY,[]);if(globalNotes.length||globalCollections.length){const courseId=newId();const{error}=await supabase.from("courses").insert({id:courseId,user_id:userId,name:"My Notes",description:"Imported from your previous notes.",color:"sky"});if(error)throw error;const map=new Map<string,string>();for(const c of globalCollections){const id=newId();const{error}=await supabase.from("collections").insert({id,user_id:userId,course_id:courseId,name:c.name});if(error)throw error;map.set(c.id,id)}for(const n of globalNotes){const sourceId=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(n.id)?n.id:null;const{error}=await supabase.from("notes").insert({id:newId(),user_id:userId,course_id:courseId,collection_id:n.collectionId?(map.get(n.collectionId)??null):null,title:n.title??"Untitled note",body:n.body??"",favorite:Boolean(n.favorite),updated_at:new Date(n.updatedAt??Date.now()).toISOString(),source_id:sourceId});if(error&&sourceId){const{data:existing}=await supabase.from("notes").select("id").eq("user_id",userId).eq("source_id",sourceId).maybeSingle();if(!existing)throw error}else if(error)throw error}changed=true;}}
}
const engine=read<Record<string,number>|null>(scoped(ENGINE_KEY,userId),read<Record<string,number>|null>(ENGINE_KEY,null));const theme=localStorage.getItem(scoped(THEME_KEY,userId))??localStorage.getItem(THEME_KEY);const displayName=localStorage.getItem(scoped(DISPLAY_NAME_KEY,userId))??localStorage.getItem(DISPLAY_NAME_KEY);const{data:profile,error:pe}=await supabase.from("profiles").select("id,theme,display_name,liquid_density,liquid_transparency,liquid_clearness,liquid_gel,liquid_bounce_stiffness,liquid_bounce_damping").eq("id",userId).maybeSingle();if(pe)throw pe;const patch:Record<string,unknown>={};if(engine){for(const[k,v]of Object.entries({liquid_density:engine.density,liquid_transparency:engine.transparency,liquid_clearness:engine.clearness,liquid_gel:engine.gel,liquid_bounce_stiffness:engine.bounceStiffness,liquid_bounce_damping:engine.bounceDamping}))if(typeof v==="number")patch[k]=v}if((theme==="light"||theme==="dark")&&!profile?.theme)patch.theme=theme;if(displayName&& !profile?.display_name)patch.display_name=displayName;if(Object.keys(patch).length){const{error}=await supabase.from("profiles").upsert({id:userId,...patch});if(error)throw error;changed=true}
localStorage.setItem(flag,"1");return changed}catch{return false}}
