import { createFileRoute } from "@tanstack/react-router";
import { AnimatePresence, motion } from "motion/react";
import { AuthPage } from "@/components/auth/AuthPage";
import { CourseGrid } from "@/components/courses/CourseGrid";
import { CourseNotesView } from "@/components/courses/CourseNotesView";
import { PwaInstallButton } from "@/components/pwa/PwaInstallButton";
import { AuthProvider, useAuth } from "@/context/AuthContext";
import { CustomizationProvider } from "@/context/CustomizationContext";
import { useCourses, useCourseStats } from "@/hooks/useCourses";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"Glass Notes — Liquid Glass course workspaces"},{name:"description",content:"Course folders open into an isolated Liquid Glass notes workspace."}]}),component:Page,ssr:false});
function Page(){return <AuthProvider><CustomizationProvider><AuthenticatedWorkspace/><PwaInstallButton/></CustomizationProvider></AuthProvider>}
function AuthenticatedWorkspace(){const{user,loading,logout}=useAuth();if(loading)return <div className="flex min-h-screen items-center justify-center bg-[#07070c] text-sm text-slate-300">Loading your workspace…</div>;if(!user)return <AuthPage/>;return <Workspace userId={user.id} email={user.email} onLogout={()=>void logout()}/>}
function Workspace({userId,email,onLogout}:{userId:string;email:string|null;onLogout:()=>void}){const{courses,addCourse,deleteCourse}=useCourses(userId);const{data:stats}=useCourseStats(userId);const[selectedCourseId,setSelectedCourseId]=useState<string|null>(null);const selectedCourse=courses.find(c=>c.id===selectedCourseId)??null;const noteCounts=stats?.counts??{};const lastEdited=stats?.lastEdited??{};return <div className="fixed inset-0 z-10 overflow-hidden bg-[#07070c]"><main className="liquid-stage relative flex h-full w-full overflow-hidden p-[10px]"><div className="liquid-orb liquid-orb-a" aria-hidden/><div className="liquid-orb liquid-orb-b" aria-hidden/><div className="liquid-orb liquid-orb-c" aria-hidden/><div className="relative min-h-0 w-full flex-1"><AnimatePresence mode="wait" initial={false}>{selectedCourse?<motion.div key={`course-${selectedCourse.id}`} className="absolute inset-0 p-[10px]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.28,ease:"easeInOut"}}><CourseNotesView course={selectedCourse} userId={userId} email={email} onLogout={onLogout} onBack={()=>setSelectedCourseId(null)}/></motion.div>:<motion.div key="course-grid" className="absolute inset-0" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.28,ease:"easeInOut"}}><CourseGrid courses={courses} noteCounts={noteCounts} lastEdited={lastEdited} hiddenCourseId={null} onOpenCourse={setSelectedCourseId} onCreateCourse={addCourse} onDeleteCourse={deleteCourse} userId={userId} email={email} onLogout={onLogout}/></motion.div>}</AnimatePresence></div></main></div>}
