import { useMemo, useState } from "react";
import { ArchiveRestore, BookOpen, Check, Download, Flame, ListTree, RotateCcw, Tags, Timer, Trophy, Upload, X } from "lucide-react";
import type { Note } from "@/hooks/useNotes";
import { cn } from "@/lib/utils";

type Props = { courseName: string; notes: Note[]; onRestoreNote: (note: Note) => void };
const POM_KEY = "glass-notes-pomodoro-v1";
const TRASH_KEY = "glass-notes-trash-v1";

export function StudyFeaturesPanel({ courseName, notes, onRestoreNote }: Props) {
  const [tab, setTab] = useState<"overview" | "study" | "backup" | "trash">("overview");
  const [focus, setFocus] = useState(false);
  const [minutes, setMinutes] = useState(25);
  const [backupMessage, setBackupMessage] = useState("");
  const [trash, setTrash] = useState<Note[]>(() => { try { return JSON.parse(localStorage.getItem(TRASH_KEY) ?? "[]") as Note[]; } catch { return []; } });
  const headings = useMemo(() => notes.flatMap((n) => n.body.split("\n").filter((line) => /^#{1,3}\s+/.test(line)).map((line) => ({ note: n.title, heading: line.replace(/^#{1,3}\s+/, "") }))), [notes]);
  const tags = useMemo(() => Array.from(new Set(notes.flatMap((n) => n.body.match(/#[A-Za-z0-9_-]+/g) ?? []))).sort(), [notes]);
  const progress = Math.min(100, notes.length * 10);
  const stats = useMemo(() => { try { return JSON.parse(localStorage.getItem(POM_KEY) ?? '{"sessions":0,"minutes":0}') as { sessions:number; minutes:number }; } catch { return { sessions: 0, minutes: 0 }; } }, [focus]);
  const achievements = [notes.length >= 1 && "First note", notes.length >= 10 && "10 notes", stats.sessions >= 5 && "5 focus sessions", stats.minutes >= 300 && "5 focus hours"].filter(Boolean) as string[];
  const startPomodoro = () => { const next = { sessions: stats.sessions + 1, minutes: stats.minutes + minutes }; localStorage.setItem(POM_KEY, JSON.stringify(next)); setFocus(true); };
  const exportBackup = () => { const payload = JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), course: courseName, notes }, null, 2); const blob = new Blob([payload], { type: "application/json" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `${courseName.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-backup.json`; a.click(); URL.revokeObjectURL(a.href); setBackupMessage("Backup exported"); };
  const importBackup = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { const data = JSON.parse(String(reader.result)); if (!Array.isArray(data.notes)) throw new Error("Invalid backup"); localStorage.setItem("glass-notes-last-import-v1", JSON.stringify(data)); setBackupMessage(`${data.notes.length} notes verified. Import requires the existing note API to avoid overwriting cloud data.`); } catch { setBackupMessage("Invalid backup file"); } }; reader.readAsText(file); };
  const restoreTrash = (note: Note) => { onRestoreNote(note); const next = trash.filter((n) => n.id !== note.id); setTrash(next); localStorage.setItem(TRASH_KEY, JSON.stringify(next)); };
  const removeTrash = (note: Note) => { const next = trash.filter((n) => n.id !== note.id); setTrash(next); localStorage.setItem(TRASH_KEY, JSON.stringify(next)); };

  return <div className="mt-3 rounded-[26px] border border-white/20 bg-white/[0.07] p-3 shadow-[inset_0_1px_2px_rgba(255,255,255,.25)] backdrop-blur-2xl">
    <div className="flex flex-wrap items-center gap-1.5">{(["overview","study","backup","trash"] as const).map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={cn("rounded-xl px-3 py-2 text-xs font-medium capitalize transition", tab === item ? "bg-white/20 text-foreground" : "text-muted-foreground hover:bg-white/10 hover:text-foreground")}>{item}</button>)}</div>
    {tab === "overview" && <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><BookOpen className="size-4" />Progress</div><p className="mt-2 text-xl font-semibold">{progress}%</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-foreground/70" style={{ width: `${progress}%` }} /></div></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Timer className="size-4" />Focus</div><p className="mt-2 text-xl font-semibold">{stats.minutes}m</p><p className="text-[11px] text-muted-foreground">{stats.sessions} sessions</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Tags className="size-4" />Tags</div><p className="mt-2 text-xl font-semibold">{tags.length}</p><p className="truncate text-[11px] text-muted-foreground">{tags.slice(0,3).join(" · ") || "No #tags yet"}</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Trophy className="size-4" />Achievements</div><p className="mt-2 text-xl font-semibold">{achievements.length}/4</p><p className="text-[11px] text-muted-foreground">{achievements.join(" · ") || "Start studying"}</p></div></div>}
    {tab === "study" && <div className="mt-3 space-y-3"><div className="flex items-center justify-between rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div><p className="text-sm font-semibold">Study Mode</p><p className="text-xs text-muted-foreground">Focus on this course without distractions.</p></div><button type="button" onClick={() => setFocus((v) => !v)} className="rounded-xl bg-foreground px-3 py-2 text-xs font-semibold text-background">{focus ? "Exit Study Mode" : "Start Study Mode"}</button></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center gap-2"><Timer className="size-4" /><p className="text-sm font-semibold">Pomodoro</p></div><div className="mt-3 flex items-center gap-2"><input aria-label="Pomodoro minutes" type="number" min={1} max={120} value={minutes} onChange={(e) => setMinutes(Math.min(120, Math.max(1, Number(e.target.value) || 1)))} className="w-24 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-sm" /><span className="text-xs text-muted-foreground">minutes</span><button type="button" onClick={startPomodoro} className="ml-auto rounded-xl bg-white/15 px-3 py-2 text-xs font-semibold hover:bg-white/20">Log focus session</button></div></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center gap-2"><ListTree className="size-4" /><p className="text-sm font-semibold">Table of Contents</p></div><div className="mt-2 max-h-32 space-y-1 overflow-auto">{headings.length ? headings.map((h, i) => <p key={`${h.note}-${i}`} className="text-xs text-muted-foreground"><span className="text-foreground">{h.heading}</span><span className="ml-2 opacity-60">{h.note}</span></p>) : <p className="text-xs text-muted-foreground">Add Markdown headings such as ## Topic to build a table of contents.</p>}</div></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center gap-2"><Flame className="size-4" /><p className="text-sm font-semibold">Achievements</p></div><div className="mt-2 flex flex-wrap gap-2">{achievements.map((a) => <span key={a} className="rounded-full bg-white/10 px-2.5 py-1 text-[11px]">{a}</span>)}{!achievements.length && <span className="text-xs text-muted-foreground">Create notes and complete focus sessions to unlock achievements.</span>}</div></div></div>}
    {tab === "backup" && <div className="mt-3 rounded-2xl border border-white/15 bg-white/[0.05] p-4"><p className="text-sm font-semibold">Backup & Restore</p><p className="mt-1 text-xs text-muted-foreground">Export this course's current notes to a portable JSON backup. Import validates a backup without silently overwriting Supabase data.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={exportBackup} className="flex items-center gap-2 rounded-xl bg-foreground px-3 py-2 text-xs font-semibold text-background"><Download className="size-3.5" />Export backup</button><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-semibold"><Upload className="size-3.5" />Verify backup<input type="file" accept="application/json,.json" className="hidden" onChange={(e) => { const f=e.target.files?.[0]; if(f) importBackup(f); }} /></label></div>{backupMessage && <p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><Check className="size-3.5" />{backupMessage}</p>}</div>}
    {tab === "trash" && <div className="mt-3 rounded-2xl border border-white/15 bg-white/[0.05] p-4"><p className="text-sm font-semibold">Recently Deleted</p>{trash.length ? <div className="mt-3 space-y-2">{trash.map((note) => <div key={note.id} className="flex items-center gap-2 rounded-xl bg-white/5 p-2"><span className="min-w-0 flex-1 truncate text-xs">{note.title}</span><button type="button" onClick={() => restoreTrash(note)} className="rounded-lg bg-white/10 px-2 py-1 text-[11px]">Restore</button><button type="button" onClick={() => removeTrash(note)} className="rounded-lg p-1 text-muted-foreground hover:bg-white/10" aria-label={`Permanently remove ${note.title}`}><X className="size-3.5" /></button></div>)}</div> : <p className="mt-2 text-xs text-muted-foreground">No deleted notes in this device's recovery list.</p>}<p className="mt-3 text-[11px] text-muted-foreground">Deleted-note recovery is kept separately from the cloud until the existing note API supports safe restoration.</p></div>}
  </div>;
}
