import { useEffect, useMemo, useRef, useState } from "react";
import { ArchiveRestore, BookOpen, Download, ListTree, Redo2, Tags, Timer, Trophy, Undo2, Upload, X } from "lucide-react";
import type { Collection, Note } from "@/hooks/useNotes";
import { cn } from "@/lib/utils";

type Props={courseName:string;courseId:string;userId:string;notes:Note[];collections:Collection[];selectedId:string|null;onSelectNote:(id:string)=>void;onCreateNote:()=>string;onUpdateNote:(id:string,patch:Partial<Omit<Note,"id">>)=>void;onDeleteNote:(note:Note)=>void;onToggleFavorite:(id:string)=>void;onRestoreNote:(note:Note)=>void;onRestoreCollection:(collection:{id?:string|null;name:string})=>string|null};
type HistoryState={past:Note[];future:Note[]};
type BackupPayload={version?:number;course?:{id?:string;name?:string};collections?:unknown[];notes:unknown[]};
const storageKey=(prefix:string,userId:string,courseId:string)=>`${prefix}:${userId}:${courseId}`;
function uniqueById(items:Note[]){return Array.from(new Map(items.map(note=>[note.id,note])).values());}
function readJSON<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw)as T:fallback}catch{return fallback;}}
function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==="object"&&value!==null;}

export function StudyFeaturesPanel(props:Props){
  const{courseName,courseId,userId,notes,collections,selectedId,onSelectNote,onCreateNote,onUpdateNote,onDeleteNote,onToggleFavorite,onRestoreNote,onRestoreCollection}=props;
  const uniqueNotes=useMemo(()=>uniqueById(notes),[notes]);
  const[tab,setTab]=useState<"overview"|"study"|"backup"|"trash"|"tags"|"history">("overview");
  const[studyMode,setStudyMode]=useState(false);const[pomRunning,setPomRunning]=useState(false);const[pomMinutes,setPomMinutes]=useState(25);const[pomSeconds,setPomSeconds]=useState(25*60);
  const[pomCompleted,setPomCompleted]=useState(()=>readJSON(storageKey("glass-notes-pomodoro-v2",userId,courseId),{sessions:0,minutes:0}));
  const[backupMessage,setBackupMessage]=useState("");
  const[trash,setTrash]=useState<Note[]>(()=>uniqueById(readJSON(storageKey("glass-notes-trash-v2",userId,courseId),[])));
  const[history,setHistory]=useState<HistoryState>(()=>readJSON(storageKey("glass-notes-history-v2",userId,courseId),{past:[],future:[]}));
  const[tagFilter,setTagFilter]=useState("");
  const previousNotesRef=useRef<Map<string,Note>>(new Map(uniqueNotes.map(note=>[note.id,note])));const restoringHistoryRef=useRef(false);const skipHistoryRef=useRef(false);const initializedStorageKeyRef=useRef("");

  useEffect(()=>{const key=storageKey("study-feature-state",userId,courseId);initializedStorageKeyRef.current="";setTrash(uniqueById(readJSON(storageKey("glass-notes-trash-v2",userId,courseId),[])));setHistory(readJSON(storageKey("glass-notes-history-v2",userId,courseId),{past:[],future:[]}));setPomCompleted(readJSON(storageKey("glass-notes-pomodoro-v2",userId,courseId),{sessions:0,minutes:0}));setTagFilter("");setPomSeconds(25*60);setPomRunning(false);setStudyMode(false);previousNotesRef.current=new Map(uniqueNotes.map(note=>[note.id,note]));skipHistoryRef.current=true;},[courseId,userId]);
  useEffect(()=>{if(initializedStorageKeyRef.current!==storageKey("study-feature-state",userId,courseId))return;try{localStorage.setItem(storageKey("glass-notes-history-v2",userId,courseId),JSON.stringify(history));}catch{}},[history,userId,courseId]);
  useEffect(()=>{if(initializedStorageKeyRef.current!==storageKey("study-feature-state",userId,courseId))return;try{localStorage.setItem(storageKey("glass-notes-pomodoro-v2",userId,courseId),JSON.stringify(pomCompleted));}catch{}},[pomCompleted,userId,courseId]);
  useEffect(()=>{if(initializedStorageKeyRef.current!==storageKey("study-feature-state",userId,courseId))return;try{localStorage.setItem(storageKey("glass-notes-trash-v2",userId,courseId),JSON.stringify(trash));}catch{}},[trash,userId,courseId]);
  useEffect(()=>{initializedStorageKeyRef.current=storageKey("study-feature-state",userId,courseId);},[courseId,userId]);
  useEffect(()=>{if(!pomRunning)return;const timer=window.setInterval(()=>setPomSeconds(value=>{if(value<=1){setPomRunning(false);setPomCompleted(current=>({sessions:current.sessions+1,minutes:current.minutes+pomMinutes}));return 0;}return value-1;}),1000);return()=>window.clearInterval(timer);},[pomRunning,pomMinutes]);
  useEffect(()=>{if(skipHistoryRef.current){skipHistoryRef.current=false;previousNotesRef.current=new Map(uniqueNotes.map(note=>[note.id,note]));return;}if(restoringHistoryRef.current){restoringHistoryRef.current=false;previousNotesRef.current=new Map(uniqueNotes.map(note=>[note.id,note]));return;}const previous=previousNotesRef.current,next=new Map(uniqueNotes.map(note=>[note.id,note])),snapshots:Note[]=[];previous.forEach((oldNote,id)=>{const current=next.get(id);if(!current||JSON.stringify(current)!==JSON.stringify(oldNote))snapshots.push(oldNote);});if(snapshots.length)setHistory(current=>({past:[...current.past,...snapshots],future:[]}));previousNotesRef.current=next;},[uniqueNotes]);

  const headings=useMemo(()=>uniqueNotes.flatMap(note=>note.body.split("\n").filter(line=>/^#{1,3}\s+/.test(line)).map(line=>({note,heading:line.replace(/^#{1,3}\s+/,"")}))),[uniqueNotes]);
  const tags=useMemo(()=>Array.from(new Set(uniqueNotes.flatMap(note=>note.body.match(/#[A-Za-z0-9_-]+/g)??[]))).sort(),[uniqueNotes]);
  const taggedNotes=useMemo(()=>uniqueNotes.filter(note=>!tagFilter||note.body.toLowerCase().includes(tagFilter.toLowerCase())||note.title.toLowerCase().includes(tagFilter.toLowerCase())),[uniqueNotes,tagFilter]);
  const selected=uniqueNotes.find(note=>note.id===selectedId)??null;const progress=Math.min(100,uniqueNotes.length*10);
  const achievements=[uniqueNotes.length>=1&&"First note",uniqueNotes.length>=10&&"10 notes",pomCompleted.sessions>=5&&"5 focus sessions",pomCompleted.minutes>=300&&"5 focus hours"].filter(Boolean)as string[];
  const formatTime=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;

  const moveToTrash=(note:Note)=>{setTrash(current=>[note,...current.filter(item=>item.id!==note.id)]);onDeleteNote(note);};
  const restoreTrash=(note:Note)=>{onRestoreNote(note);onSelectNote(note.id);setTrash(current=>current.filter(item=>item.id!==note.id));};
  const removeTrash=(note:Note)=>setTrash(current=>current.filter(item=>item.id!==note.id));
  const undo=()=>{const previous=history.past.at(-1);if(!previous)return;restoringHistoryRef.current=true;setHistory(current=>({past:current.past.slice(0,-1),future:[selected??previous,...current.future]}));onRestoreNote(previous);onSelectNote(previous.id);};
  const redo=()=>{const next=history.future[0];if(!next)return;restoringHistoryRef.current=true;setHistory(current=>({past:[...current.past,selected??next],future:current.future.slice(1)}));onRestoreNote(next);onSelectNote(next.id);};

  const exportBackup=()=>{const payload={version:4,exportedAt:new Date().toISOString(),course:{id:courseId,name:courseName},collections,notes:uniqueNotes};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`${courseName.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-backup.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),0);setBackupMessage("Course, collections, and notes exported successfully.");};
  const importBackup=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{const parsed:unknown=JSON.parse(String(reader.result));if(!isRecord(parsed)||!Array.isArray(parsed.notes))throw new Error("Invalid notes payload");const data=parsed as BackupPayload;const collectionMap=new Map<string,string>();const backupCollections=Array.isArray(data.collections)?data.collections:[];for(const rawCollection of backupCollections){if(!isRecord(rawCollection)||typeof rawCollection.name!=="string")continue;const restoredId=onRestoreCollection({id:typeof rawCollection.id==="string"?rawCollection.id:null,name:rawCollection.name.trim()});if(restoredId&&typeof rawCollection.id==="string")collectionMap.set(rawCollection.id,restoredId);}let restoredCount=0;for(const rawNote of data.notes){if(!isRecord(rawNote))continue;const title=typeof rawNote.title==="string"?rawNote.title:"Untitled note";const body=typeof rawNote.body==="string"?rawNote.body:"";const originalId=typeof rawNote.id==="string"?rawNote.id:null;const originalSource=typeof rawNote.sourceId==="string"?rawNote.sourceId:null;const mappedCollection=typeof rawNote.collectionId==="string"?(collectionMap.get(rawNote.collectionId)??null):null;onRestoreNote({id:originalId??"",sourceId:originalSource,title,body,favorite:typeof rawNote.favorite==="boolean"?rawNote.favorite:false,collectionId:mappedCollection,revision:typeof rawNote.revision==="number"?rawNote.revision:0,createdAt:typeof rawNote.createdAt==="number"?rawNote.createdAt:Date.now(),updatedAt:typeof rawNote.updatedAt==="number"?rawNote.updatedAt:Date.now()});restoredCount++;}setBackupMessage(`Restored ${restoredCount} notes with collection structure.`);}catch{setBackupMessage("Invalid backup file. Nothing was restored.");}};reader.readAsText(file);};

  return <section className="mt-3 rounded-[26px] border border-white/20 bg-white/[0.07] p-3 shadow-[inset_0_1px_2px_rgba(255,255,255,.25)] backdrop-blur-2xl">
    <div className="flex flex-wrap items-center gap-1.5">{([["overview","Overview"],["study","Study"],["backup","Backup"],["trash","Trash"],["tags","Tags"],["history","History"]] as const).map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id)} className={cn("rounded-xl px-3 py-2 text-xs font-medium transition",tab===id?"bg-white/20 text-foreground":"text-muted-foreground hover:bg-white/10 hover:text-foreground")}>{label}</button>)}<button type="button" onClick={()=>{const id=onCreateNote();if(id)onSelectNote(id)}} className="ml-auto rounded-xl bg-foreground px-3 py-2 text-xs font-semibold text-background">New note</button></div>
    {tab==="overview"&&<div className="mt-3 space-y-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><BookOpen className="size-4"/>Progress</div><p className="mt-2 text-xl font-semibold">{progress}%</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Timer className="size-4"/>Focus</div><p className="mt-2 text-xl font-semibold">{pomCompleted.minutes}m</p><p className="text-[11px] text-muted-foreground">{pomCompleted.sessions} completed sessions</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Tags className="size-4"/>Tags</div><p className="mt-2 text-xl font-semibold">{tags.length}</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Trophy className="size-4"/>Achievements</div><p className="mt-2 text-xl font-semibold">{achievements.length}</p></div></div>{selected&&<div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-[11px] uppercase tracking-[0.18em] text-muted-foreground">Selected note</p><p className="mt-1 truncate text-sm font-semibold">{selected.title}</p></div><button type="button" onClick={()=>moveToTrash(selected)} className="shrink-0 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs">Delete</button></div><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>onToggleFavorite(selected.id)} className="rounded-xl bg-white/10 px-3 py-2 text-xs">{selected.favorite?"Remove favorite":"Add favorite"}</button><button type="button" onClick={()=>onUpdateNote(selected.id,{title:"Untitled note"})} className="rounded-xl bg-white/10 px-3 py-2 text-xs">Reset title</button></div></div>}</div>}
    {tab==="study"&&<div className="mt-3 space-y-3"><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Study Mode</p><p className="text-xs text-muted-foreground">Read through one course without mixing it with Pomodoro state.</p></div><button type="button" onClick={()=>setStudyMode(value=>!value)} className="rounded-xl bg-foreground px-3 py-2 text-xs font-semibold text-background">{studyMode?"Exit Study Mode":"Start Study Mode"}</button></div>{studyMode&&<div className="mt-4 space-y-2">{uniqueNotes.map((note,index)=><article key={note.id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><p className="text-[10px] text-muted-foreground">{index+1} / {uniqueNotes.length}</p><button type="button" onClick={()=>onSelectNote(note.id)} className="mt-1 text-left text-sm font-semibold hover:underline">{note.title}</button></article>)}</div>}</div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center gap-2"><Timer className="size-4"/><p className="text-sm font-semibold">Pomodoro</p></div><div className="mt-3 flex flex-wrap items-center gap-2"><input aria-label="Pomodoro minutes" type="number" min={1} max={120} value={pomMinutes} onChange={event=>{const minutes=Math.min(120,Math.max(1,Number(event.target.value)||1));setPomMinutes(minutes);if(!pomRunning)setPomSeconds(minutes*60);}} className="w-24 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-sm"/><span className="text-xs text-muted-foreground">minutes</span><span className="font-mono text-lg tabular-nums">{formatTime(pomSeconds)}</span><button type="button" onClick={()=>{if(pomRunning)setPomRunning(false);else{setPomSeconds(pomMinutes*60);setPomRunning(true);}}} className="ml-auto rounded-xl bg-white/15 px-3 py-2 text-xs font-semibold">{pomRunning?"Pause":"Start"}</button><button type="button" disabled={pomRunning} onClick={()=>setPomSeconds(pomMinutes*60)} className="rounded-xl bg-white/10 px-3 py-2 text-xs disabled:opacity-40">Reset</button></div></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center gap-2"><ListTree className="size-4"/><p className="text-sm font-semibold">Table of Contents</p></div><div className="mt-2 max-h-40 space-y-1 overflow-auto">{headings.length?headings.map((item,index)=><button key={`${item.note.id}-${index}`} type="button" onClick={()=>onSelectNote(item.note.id)} className="block w-full rounded-lg px-2 py-1 text-left text-xs hover:bg-white/10">{item.note.title} · {item.heading}</button>):<p className="text-xs text-muted-foreground">Add Markdown headings to notes to build a table of contents.</p>}</div></div></div>}
    {tab==="tags"&&<div className="mt-3"><div className="flex items-center gap-2"><Tags className="size-4 text-muted-foreground"/><input value={tagFilter} onChange={event=>setTagFilter(event.target.value)} placeholder="Search notes or tags" className="w-full rounded-xl border border-white/10 bg-white/[0.05] px-3 py-2 text-sm outline-none"/></div><div className="mt-3 flex flex-wrap gap-2">{tags.length?tags.map(tag=><button key={tag} type="button" onClick={()=>setTagFilter(tag)} className="rounded-full border border-white/15 bg-white/[0.06] px-3 py-1 text-xs">{tag}</button>):<span className="text-xs text-muted-foreground">No #tags yet.</span>}</div><div className="mt-3 space-y-1">{taggedNotes.map(note=><div key={note.id} className="flex items-center justify-between rounded-xl bg-white/[0.04] px-3 py-2"><button type="button" onClick={()=>onSelectNote(note.id)} className="truncate text-left text-xs">{note.title}</button><button type="button" onClick={()=>moveToTrash(note)} aria-label={`Delete ${note.title}`} className="rounded-full p-1.5 text-muted-foreground hover:bg-white/10"><X className="size-3.5"/></button></div>)}</div></div>}
    {tab==="backup"&&<div className="mt-3 space-y-3"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-3 text-xs text-muted-foreground">Backups include this course, all collections, and every note. Restore maps collection IDs and uses note IDs/source identity safely.</div><button type="button" onClick={exportBackup} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/[0.07] px-4 py-3 text-sm"><Download className="size-4"/>Export complete course backup</button><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/[0.07] px-4 py-3 text-sm"><Upload className="size-4"/>Restore backup<input type="file" accept="application/json,.json" className="hidden" onChange={event=>{const file=event.target.files?.[0];if(file)importBackup(file);event.currentTarget.value="";}}/></label>{backupMessage&&<p className="rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-xs text-muted-foreground">{backupMessage}</p>}</div>}
    {tab==="trash"&&<div className="mt-3 space-y-2">{trash.length?trash.map(note=><div key={note.id} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-3"><ArchiveRestore className="size-4 shrink-0 text-muted-foreground"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{note.title}</p><p className="text-[10px] text-muted-foreground">Recently deleted from {courseName}</p></div><button type="button" onClick={()=>restoreTrash(note)} className="rounded-xl bg-white/10 px-3 py-2 text-xs">Restore</button><button type="button" onClick={()=>removeTrash(note)} className="rounded-xl bg-white/5 px-3 py-2 text-xs text-muted-foreground">Remove</button></div>):<p className="rounded-2xl border border-dashed border-white/10 p-5 text-center text-xs text-muted-foreground">Trash is empty.</p>}</div>}
    {tab==="history"&&<div className="mt-3 rounded-2xl border border-white/15 bg-white/[0.05] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Recent edit history</p><p className="text-xs text-muted-foreground">Undo and redo recent local edit snapshots for this course.</p></div><div className="flex gap-2"><button type="button" onClick={undo} disabled={!history.past.length} className="rounded-xl bg-white/10 px-3 py-2 text-xs disabled:opacity-40"><Undo2 className="mr-1 inline size-3.5"/>Undo</button><button type="button" onClick={redo} disabled={!history.future.length} className="rounded-xl bg-white/10 px-3 py-2 text-xs disabled:opacity-40"><Redo2 className="mr-1 inline size-3.5"/>Redo</button></div></div><div className="mt-3 space-y-1">{history.past.slice(-8).reverse().map((note,index)=><button key={`${note.id}-${index}`} type="button" onClick={()=>onSelectNote(note.id)} className="block w-full rounded-xl border border-white/5 bg-white/[0.03] px-3 py-2 text-left text-xs hover:bg-white/[0.07]">{note.title}</button>)}{!history.past.length&&<p className="text-xs text-muted-foreground">No local edit history yet.</p>}</div></div>}
  </section>;
}
