import { useMemo, useState } from "react";
import { Award, BookOpen, Clock3, Download, FileDown, History, ListTree, RotateCcw, Search, Tag, Trash2, Upload, Undo2, Redo2 } from "lucide-react";
import type { Course } from "@/hooks/useCourses";
import type { Note } from "@/hooks/useNotes";
import { getAchievements, readStudyProgress } from "./studyFeatures";

type Props = { course: Course; notes: Note[]; onUpdateNote?: (id: string, patch: Partial<Note>) => void; onDeleteNote?: (id: string) => void; onRestoreNote?: (id: string) => void };

export function StudyToolsPanel({ course, notes, onUpdateNote, onDeleteNote, onRestoreNote }: Props) {
  const [tab, setTab] = useState<"overview" | "tags" | "study" | "backup">("overview");
  const [query, setQuery] = useState("");
  const [study, setStudy] = useState(false);
  const progress = readStudyProgress();
  const achievements = getAchievements(progress);
  const filtered = useMemo(() => notes.filter(n => !query || n.title.toLowerCase().includes(query.toLowerCase()) || n.content.toLowerCase().includes(query.toLowerCase())), [notes, query]);
  const tags = useMemo(() => Array.from(new Set(notes.flatMap(n => (n.content.match(/#[a-zA-Z0-9_-]+/g) ?? []).map(t => t.slice(1))))), [notes]);
  const downloadBackup = () => { const blob = new Blob([JSON.stringify({ version: 1, exportedAt: new Date().toISOString(), course, notes }, null, 2)], { type: "application/json" }); const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `${course.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-backup.json`; a.click(); URL.revokeObjectURL(a.href); };
  const restoreFile = async (file: File) => { const data = JSON.parse(await file.text()) as { notes?: Note[] }; for (const note of data.notes ?? []) { if (onUpdateNote) onUpdateNote(note.id, { title: note.title, content: note.content, favorite: note.favorite, collection_id: note.collection_id }); } };
  return <section className="rounded-3xl border border-white/20 bg-white/[0.07] p-4 backdrop-blur-2xl">
    <div className="flex flex-wrap gap-2">{([["overview", Award, "Progress"],["tags", Tag, "Tags"],["study", BookOpen, "Study Mode"],["backup", Download, "Backup"]] as const).map(([id, Icon, label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex items-center gap-2 rounded-2xl border border-white/15 px-3 py-2 text-xs ${tab === id ? "bg-white/15" : "bg-white/[0.04]"}`}><Icon className="size-3.5" />{label}</button>)}</div>
    {tab === "overview" && <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><p className="text-xs text-muted-foreground">Notes</p><p className="mt-1 text-2xl font-semibold">{notes.length}</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><p className="text-xs text-muted-foreground">Focus time</p><p className="mt-1 text-2xl font-semibold">{progress.totalFocusMinutes}m</p></div><div className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><p className="text-xs text-muted-foreground">Streak</p><p className="mt-1 text-2xl font-semibold">{progress.streakDays}d</p></div><div className="sm:col-span-3 flex flex-wrap gap-2">{achievements.map(a => <span key={a} className="rounded-full border border-white/15 bg-white/[0.06] px-3 py-1 text-xs">🏆 {a}</span>)}</div></div>}
    {tab === "tags" && <div className="mt-4"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search notes" className="w-full rounded-2xl border border-white/15 bg-white/[0.06] py-2.5 pl-9 pr-3 text-sm outline-none" /></div><div className="mt-3 flex flex-wrap gap-2">{tags.length ? tags.map(t => <button key={t} type="button" onClick={() => setQuery(`#${t}`)} className="rounded-full border border-white/15 bg-white/[0.06] px-3 py-1 text-xs">#{t}</button>) : <p className="text-xs text-muted-foreground">Add #tags to note content to organize them.</p>}</div><div className="mt-3 space-y-1">{filtered.map(n => <div key={n.id} className="flex items-center justify-between rounded-xl bg-white/[0.04] px-3 py-2 text-xs"><span className="truncate">{n.title}</span>{onDeleteNote && <button type="button" onClick={() => onDeleteNote(n.id)} aria-label={`Delete ${n.title}`}><Trash2 className="size-3.5" /></button>}</div>)}</div></div>}
    {tab === "study" && <div className="mt-4 rounded-2xl border border-white/15 bg-white/[0.05] p-5"><BookOpen className="size-6" /><h3 className="mt-3 font-semibold">{course.name} Study Mode</h3><p className="mt-1 text-xs text-muted-foreground">Focus on one note at a time without leaving this course.</p><button type="button" onClick={() => setStudy(!study)} className="mt-4 rounded-2xl bg-foreground px-4 py-2 text-xs font-semibold text-background">{study ? "Exit Study Mode" : "Start Study Mode"}</button>{study && <div className="mt-4 space-y-2">{filtered.map((n, i) => <article key={n.id} className="rounded-2xl border border-white/15 bg-white/[0.05] p-4"><p className="text-[10px] text-muted-foreground">{i + 1} / {filtered.length}</p><h4 className="mt-1 font-semibold">{n.title}</h4><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{n.content}</p></article>)}</div>}</div>}
    {tab === "backup" && <div className="mt-4 space-y-3"><button type="button" onClick={downloadBackup} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/[0.07] px-4 py-3 text-sm"><FileDown className="size-4" />Export course backup</button><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-white/15 bg-white/[0.07] px-4 py-3 text-sm"><Upload className="size-4" />Restore from backup<input type="file" accept="application/json,.json" className="hidden" onChange={e => e.target.files?.[0] && restoreFile(e.target.files[0])} /></label><p className="text-[11px] text-muted-foreground">Backups are JSON copies. Existing note IDs are preserved so compatible restores can update stored notes.</p></div>}
  </section>;
}
