import { BookOpen, CalendarDays, Clock3, ShieldCheck, Timer, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

import { AddCourseModal } from "@/components/courses/AddCoursesModal";
import { CourseCard } from "@/components/courses/CourseCard";
import { PomodoroModal } from "@/components/focus/PomodoroModal";
import { EngineSettingsModal } from "@/components/liquid/EngineSettingsModal";
import { ThemeToggle } from "@/components/liquid/ThemeToggle";
import { useCustomization } from "@/context/CustomizationContext";
import type { Course, CourseAccent } from "@/hooks/useCourses";

type Props = { courses: Course[]; noteCounts: Record<string, number>; lastEdited: Record<string, number | null>; hiddenCourseId: string | null; onOpenCourse: (id: string) => void; onCreateCourse: (input: { name: string; description: string; color: CourseAccent }) => void };
const DISTRACTION_KEY = "liquid-glass-distraction-mode";
type DistractionSession = { active: boolean; courseName: string; date: string; durationHours: number; endsAt: number | null };
const DEFAULT_SESSION: DistractionSession = { active: false, courseName: "", date: new Date().toISOString().slice(0, 10), durationHours: 1, endsAt: null };
function readDistractionSession(): DistractionSession { try { const saved = JSON.parse(localStorage.getItem(DISTRACTION_KEY) ?? "null"); if (!saved) return DEFAULT_SESSION; const session = { ...DEFAULT_SESSION, ...saved } as DistractionSession; if (session.active && session.endsAt && session.endsAt <= Date.now()) return { ...session, active: false, endsAt: null }; return session; } catch { return DEFAULT_SESSION; } }

function DistractionMode({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [session, setSession] = useState<DistractionSession>(() => readDistractionSession());
  const [confirmOpen, setConfirmOpen] = useState(false);
  const save = (next: DistractionSession) => { setSession(next); localStorage.setItem(DISTRACTION_KEY, JSON.stringify(next)); };
  useEffect(() => { const sync = () => setSession(readDistractionSession()); window.addEventListener("storage", sync); return () => window.removeEventListener("storage", sync); }, []);
  const requestStart = () => setConfirmOpen(true);
  const confirmStart = () => { const hours = Math.min(24, Math.max(1, Number(session.durationHours) || 1)); const courseName = session.courseName.trim() || "Study Session"; const endsAt = Date.now() + hours * 60 * 60 * 1000; save({ ...session, active: true, courseName, durationHours: hours, endsAt }); setConfirmOpen(false); onOpenChange(false); };
  const dateLabel = useMemo(() => { const date = new Date(`${session.date}T00:00:00`); return Number.isNaN(date.getTime()) ? session.date : date.toLocaleDateString(undefined, { day: "numeric", month: "long", year: "numeric" }); }, [session.date]);
  // Active sessions are locked by the course workspace route. Never place a full-screen blocker over the dashboard here.
  if (session.active) return null;
  if (!open) return null;
  return <>
    <div className="fixed inset-0 z-[190] flex items-center justify-center bg-black/35 p-5 backdrop-blur-md" role="dialog" aria-modal="true" aria-label="Distraction Mode setup">
      <div className="w-full max-w-md rounded-[30px] border border-white/20 bg-black/35 p-6 shadow-2xl backdrop-blur-2xl sm:p-7">
        <div className="flex items-center justify-between"><div><p className="text-lg font-semibold">Distraction Mode</p><p className="mt-1 text-xs text-muted-foreground">Create a focused study session.</p></div><button type="button" onClick={() => onOpenChange(false)} className="rounded-full p-2 text-muted-foreground hover:bg-white/10" aria-label="Close"><X className="size-4" /></button></div>
        <div className="mt-6 space-y-4">
          <label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Course name</span><input value={session.courseName} onChange={(event) => setSession((current) => ({ ...current, courseName: event.target.value }))} placeholder="e.g. Accountancy" className="w-full rounded-2xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm outline-none transition focus:border-white/25" /></label>
          <div className="grid grid-cols-2 gap-3"><label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Study hours</span><input type="number" min={1} max={24} value={session.durationHours} onChange={(event) => setSession((current) => ({ ...current, durationHours: Math.min(24, Math.max(1, Number(event.target.value) || 1)) }))} className="w-full rounded-2xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm outline-none" /></label><label className="block"><span className="mb-2 block text-xs font-medium text-muted-foreground">Date</span><input type="date" value={session.date} onChange={(event) => setSession((current) => ({ ...current, date: event.target.value }))} className="w-full rounded-2xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm outline-none" /></label></div>
        </div>
        <button type="button" onClick={requestStart} className="mt-6 flex w-full items-center justify-center gap-2 rounded-2xl bg-foreground px-5 py-3 text-sm font-semibold text-background transition hover:opacity-90"><ShieldCheck className="size-4" /> Start Distraction Mode</button>
        <p className="mt-3 text-center text-[11px] leading-5 text-muted-foreground">After confirmation, the selected course stays open with full study access until the selected time ends.</p>
      </div>
    </div>
    {confirmOpen && <div className="fixed inset-0 z-[220] flex items-center justify-center bg-black/55 p-5 backdrop-blur-md" role="alertdialog" aria-modal="true" aria-labelledby="distraction-confirm-title"><div className="w-full max-w-sm rounded-[28px] border border-white/20 bg-black/45 p-6 text-center shadow-2xl backdrop-blur-2xl"><div className="mx-auto flex size-14 items-center justify-center rounded-2xl border border-white/15 bg-white/[0.07]"><ShieldCheck className="size-6" /></div><h3 id="distraction-confirm-title" className="mt-5 text-xl font-semibold">Start Distraction Mode?</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Once confirmed, you cannot turn Distraction Mode off. You keep full access inside the selected course, while leaving the course is restricted until the study time ends.</p><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" onClick={() => setConfirmOpen(false)} className="rounded-2xl border border-white/10 bg-white/[0.05] px-4 py-3 text-sm font-medium hover:bg-white/10">Cancel</button><button type="button" onClick={confirmStart} className="rounded-2xl bg-foreground px-4 py-3 text-sm font-semibold text-background hover:opacity-90">Confirm & Lock</button></div></div></div>}
  </>;
}

export function CourseGrid({ courses, noteCounts, lastEdited, hiddenCourseId, onOpenCourse, onCreateCourse }: Props) {
  const { displayName } = useCustomization(); const [pomodoroOpen, setPomodoroOpen] = useState(false); const [distractionOpen, setDistractionOpen] = useState(false); const [distractionActive, setDistractionActive] = useState(() => readDistractionSession().active);
  useEffect(() => { const sync = () => setDistractionActive(readDistractionSession().active); window.addEventListener("storage", sync); const id = window.setInterval(sync, 1000); return () => { window.removeEventListener("storage", sync); window.clearInterval(id); }; }, []);
  return <div className="flex h-full min-h-0 w-full flex-col gap-6 overflow-y-auto px-2 py-2">
    <div className="liquid-panel flex flex-wrap items-center justify-between gap-4 rounded-3xl p-5" style={{ backgroundColor: "var(--water-gel-bg)", backdropFilter: "blur(var(--liquid-density, 12px)) saturate(200%) contrast(105%)", borderTop: "1px solid rgba(255, 255, 255, 0.4)", boxShadow: "inset 0 1px 2px 0 rgba(255, 255, 255, 0.5), inset 0 -2px 4px 0 rgba(0, 0, 0, 0.25), 0 8px 32px 0 rgba(0, 0, 0, 0.37)" }}><div className="flex items-center gap-4"><span aria-hidden className="flex size-14 shrink-0 items-center justify-center rounded-full"><BookOpen className="size-6 text-white drop-shadow" /></span><div><h1 className="text-xl font-semibold tracking-tight text-foreground">Welcome back{displayName ? `, ${displayName}` : ""}! 👋</h1><p className="text-sm text-muted-foreground">Select a course folder to access your workspace</p></div></div><div className="flex items-center gap-2"><ThemeToggle /><EngineSettingsModal /></div></div>
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2"><button type="button" onClick={() => setDistractionOpen(true)} className="liquid-panel group flex min-h-28 items-center gap-4 rounded-3xl p-5 text-left transition duration-200 hover:-translate-y-0.5 hover:brightness-110" style={{ backgroundColor: "var(--water-gel-bg)", backdropFilter: "blur(var(--liquid-density, 12px)) saturate(180%)", borderTop: "1px solid rgba(255,255,255,.32)" }}><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-white/10 text-foreground shadow-inner"><ShieldCheck className="size-5" /></span><span><span className="block text-base font-semibold text-foreground">Distraction Mode</span><span className="mt-1 block text-xs text-muted-foreground">Lock the course boundary and study without distractions</span></span></button><button type="button" onClick={() => setPomodoroOpen(true)} className="liquid-panel group flex min-h-28 items-center gap-4 rounded-3xl p-5 text-left transition duration-200 hover:-translate-y-0.5 hover:brightness-110" style={{ backgroundColor: "var(--water-gel-bg)", backdropFilter: "blur(var(--liquid-density, 12px)) saturate(180%)", borderTop: "1px solid rgba(255,255,255,.32)" }}><span className="flex size-12 shrink-0 items-center justify-center rounded-2xl bg-white/10 text-foreground shadow-inner"><Timer className="size-5" /></span><span><span className="block text-base font-semibold text-foreground">Pomodoro</span><span className="mt-1 block text-xs text-muted-foreground">Focus with a timer</span></span></button></div>
    <div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-2"><span className="size-1.5 rounded-full bg-primary" aria-hidden /><h2 className="text-[0.68rem] font-bold uppercase tracking-[0.3em] text-muted-foreground on-stage-muted">Course Folders</h2></div><AddCourseModal onCreate={onCreateCourse} /></div>
    {courses.length === 0 ? <div className="flex flex-1 flex-col items-center justify-center gap-2 text-center"><p className="text-sm font-medium text-foreground on-stage">No courses yet</p><p className="max-w-xs text-xs text-muted-foreground on-stage-muted">Add your first course to start taking notes inside its own glass workspace.</p></div> : <div className="grid grid-cols-[repeat(auto-fill,minmax(240px,1fr))] gap-5">{courses.map((course) => course.id === hiddenCourseId ? <div key={course.id} className="h-52" aria-hidden /> : <CourseCard key={course.id} course={course} noteCount={noteCounts[course.id] ?? 0} lastEditedAt={lastEdited[course.id] ?? null} onOpen={() => onOpenCourse(course.id)} />)}</div>}
    <PomodoroModal open={pomodoroOpen} onOpenChange={setPomodoroOpen} /><DistractionMode open={distractionOpen} onOpenChange={(value) => { setDistractionOpen(value); setDistractionActive(readDistractionSession().active); }} />{distractionActive && !distractionOpen && <DistractionMode open={false} onOpenChange={() => setDistractionActive(false)} />}
  </div>;
}
