import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";

type AuthUser={id:string;email:string|null;user_metadata?:{display_name?:string}|undefined};
type AuthContextValue={user:AuthUser|null;loading:boolean;signInWithPassword:(email:string,password:string)=>Promise<void>;signUpWithPassword:(email:string,password:string,displayName:string)=>Promise<boolean>;resendConfirmation:(email:string)=>Promise<void>;signInWithGoogle:()=>Promise<void>;resetPassword:(email:string)=>Promise<void>;updatePassword:(newPassword:string)=>Promise<void>;logout:()=>Promise<void>};
const AuthContext=createContext<AuthContextValue|null>(null);
const ACCOUNT_STORAGE_NAMESPACE="glass-notes-account-state-v1";const ACTIVE_USER_KEY="glass-notes-active-user-v1";
const PRODUCTION_WEB_ORIGIN="https://fluid-glass-studio.lovable.app";
const FIXED_ACCOUNT_KEYS=["liquid-glass-performance-mode","liquid-glass-study-reminders","liquid-glass-pomodoro-durations","liquid-glass-pomodoro-session","liquid-glass-background-image-v1","liquid-glass-background-opacity","glass-notes-study-progress-v1"];
const ACCOUNT_KEY_PREFIXES=["glass-notes-trash-v1:","glass-notes-history-v1:","glass-notes-pomodoro-v1:"];
function isAccountStateKey(key:string){return FIXED_ACCOUNT_KEYS.includes(key)||ACCOUNT_KEY_PREFIXES.some(prefix=>key.startsWith(prefix));}
function accountSlot(userId:string,key:string){return `${ACCOUNT_STORAGE_NAMESPACE}:${userId}:${key}`;}
function isNativeCapacitorApp(){if(typeof window==="undefined")return false;return Boolean((window as typeof window & {Capacitor?:{isNativePlatform?:()=>boolean}}).Capacitor?.isNativePlatform?.());}
function authRedirect(path:string){if(typeof window==="undefined")return `${PRODUCTION_WEB_ORIGIN}${path}`;return `${isNativeCapacitorApp()?PRODUCTION_WEB_ORIGIN:window.location.origin}${path}`;}
function switchAccountBrowserState(userId:string|null,previousUserId:string|null){if(typeof window==="undefined")return;try{if(previousUserId&&previousUserId!==userId){for(const key of Object.keys(localStorage)){if(!isAccountStateKey(key))continue;const value=localStorage.getItem(key);if(value!==null)localStorage.setItem(accountSlot(previousUserId,key),value);}}if(previousUserId!==userId){for(const key of Object.keys(localStorage)){if(isAccountStateKey(key))localStorage.removeItem(key);}}if(userId&&previousUserId!==userId){const prefix=`${ACCOUNT_STORAGE_NAMESPACE}:${userId}:`;for(const key of Object.keys(localStorage)){if(!key.startsWith(prefix))continue;const originalKey=key.slice(prefix.length);const value=localStorage.getItem(key);if(value!==null)localStorage.setItem(originalKey,value);localStorage.removeItem(key);}}if(userId)localStorage.setItem(ACTIVE_USER_KEY,userId);else localStorage.removeItem(ACTIVE_USER_KEY);}catch{/* Supabase remains authoritative if browser storage is unavailable. */}}

export function AuthProvider({children}:{children:ReactNode}){const[user,setUser]=useState<AuthUser|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{let active=true;let currentStorageUserId:string|null=null;try{currentStorageUserId=localStorage.getItem(ACTIVE_USER_KEY);}catch{}const syncUser=(nextUser:{id:string;email?:string|null;user_metadata?:unknown}|null)=>{if(!active)return;const nextId=nextUser?.id??null;if(currentStorageUserId!==nextId){switchAccountBrowserState(nextId,currentStorageUserId);currentStorageUserId=nextId;}else if(nextId){try{localStorage.setItem(ACTIVE_USER_KEY,nextId);}catch{}}setUser(nextUser?{id:nextUser.id,email:nextUser.email??null,user_metadata:nextUser.user_metadata as {display_name?:string}|undefined}:null);setLoading(false);};void supabase.auth.getSession().then(({data})=>syncUser(data.session?.user??null));const{data:subscription}=supabase.auth.onAuthStateChange((_event,session)=>syncUser(session?.user??null));return()=>{active=false;subscription.subscription.unsubscribe();};},[]);const value=useMemo<AuthContextValue>(()=>({user,loading,async signInWithPassword(email,password){const{error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw new Error(error.message);},async signUpWithPassword(email,password,displayName){const normalizedEmail=email.trim();const signedUp=await supabase.auth.signUp({email:normalizedEmail,password,options:{data:{display_name:displayName.trim()},emailRedirectTo:authRedirect("/auth/callback")}});if(signedUp.error)throw new Error(signedUp.error.message);return Boolean(signedUp.data.session);},async resendConfirmation(email){const normalizedEmail=email.trim();if(!normalizedEmail)throw new Error("Enter your email address first.");const{error}=await supabase.auth.resend({type:"signup",email:normalizedEmail,options:{emailRedirectTo:authRedirect("/auth/callback")}});if(error)throw new Error(error.message);},async signInWithGoogle(){const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:authRedirect("/auth/callback"),queryParams:{access_type:"offline",prompt:"select_account"}}});if(error)throw new Error(error.message);},async resetPassword(email){const{error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:authRedirect("/reset-password")});if(error)throw new Error(error.message);},async updatePassword(newPassword){const{error}=await supabase.auth.updateUser({password:newPassword});if(error)throw new Error(error.message);},async logout(){await supabase.auth.signOut();setUser(null);}}),[loading,user]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;}
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error("useAuth must be used inside AuthProvider.");return value;}
