import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { supabase } from "@/lib/supabaseClient";

export type LiquidSettings = { density:number; transparency:number; clearness:number; gel:number; bounceStiffness:number; bounceDamping:number; saturation:number; sheen:number; refraction:number };
export const LIQUID_DEFAULTS:LiquidSettings={density:12,transparency:45,clearness:35,gel:55,bounceStiffness:200,bounceDamping:24,saturation:200,sheen:50,refraction:40};
export type Theme="light"|"dark";
type Ctx={liquid:LiquidSettings;setLiquid:(patch:Partial<LiquidSettings>)=>void;reset:()=>void;theme:Theme;setTheme:(theme:Theme)=>void;toggleTheme:()=>void;displayName:string;setDisplayName:(name:string)=>void;pureBlack:boolean;setPureBlack:(value:boolean)=>void};
const CustomizationContext=createContext<Ctx|null>(null);
const LEGACY_KEYS={liquid:"liquid-glass-engine-v1",theme:"liquid-glass-theme-v1",displayName:"liquid-glass-display-name-v1",pureBlack:"liquid-glass-pure-black-v1"};
const scoped=(key:string,userId:string)=>`${key}:${userId}`;
function clamp(v:number,min:number,max:number){return Math.min(max,Math.max(min,v));}
function sanitize(raw:unknown):LiquidSettings{const v=(raw??{})as Partial<LiquidSettings>;return{density:clamp(Number(v.density??LIQUID_DEFAULTS.density),0,40),transparency:clamp(Number(v.transparency??LIQUID_DEFAULTS.transparency),5,95),clearness:clamp(Number(v.clearness??LIQUID_DEFAULTS.clearness),0,100),gel:clamp(Number(v.gel??LIQUID_DEFAULTS.gel),0,100),bounceStiffness:clamp(Number(v.bounceStiffness??LIQUID_DEFAULTS.bounceStiffness),100,500),bounceDamping:clamp(Number(v.bounceDamping??LIQUID_DEFAULTS.bounceDamping),10,40),saturation:clamp(Number(v.saturation??LIQUID_DEFAULTS.saturation),50,250),sheen:clamp(Number(v.sheen??LIQUID_DEFAULTS.sheen),0,100),refraction:clamp(Number(v.refraction??LIQUID_DEFAULTS.refraction),0,100)};}
function readJSON<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw)as T:fallback}catch{return fallback;}}
function initialLiquid(userId:string){if(!userId||typeof window==="undefined")return LIQUID_DEFAULTS;const scopedValue=readJSON<unknown>(scoped(LEGACY_KEYS.liquid,userId),null);if(scopedValue)return sanitize(scopedValue);return sanitize(readJSON<unknown>(LEGACY_KEYS.liquid,null));}
function initialTheme(userId:string):Theme{if(typeof window==="undefined")return"light";try{const s=localStorage.getItem(scoped(LEGACY_KEYS.theme,userId))??localStorage.getItem(LEGACY_KEYS.theme);return s==="dark"||s==="light"?s:(window.matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light")}catch{return"light";}}
function initialName(userId:string){if(typeof window==="undefined")return"";try{return localStorage.getItem(scoped(LEGACY_KEYS.displayName,userId))??localStorage.getItem(LEGACY_KEYS.displayName)??""}catch{return""}}
function initialBlack(userId:string){if(typeof window==="undefined")return false;try{return localStorage.getItem(scoped(LEGACY_KEYS.pureBlack,userId))==="1"}catch{return false}}

export function CustomizationProvider({children}:{children:ReactNode}){
  const[userId,setUserId]=useState<string|null>(null);const[profileReady,setProfileReady]=useState(false);const[liquid,setLiquidState]=useState(LIQUID_DEFAULTS);const[theme,setThemeState]=useState<Theme>("light");const[displayName,setDisplayNameState]=useState("");const[pureBlack,setPureBlackState]=useState(false);
  useEffect(()=>{let active=true;const load=(id:string|null)=>{setUserId(id);setProfileReady(false);setLiquidState(initialLiquid(id??""));setThemeState(initialTheme(id??""));setDisplayNameState(initialName(id??""));setPureBlackState(initialBlack(id??""));if(!id){setProfileReady(true);return;}void supabase.from("profiles").select("theme,display_name,liquid_density,liquid_transparency,liquid_clearness,liquid_gel,liquid_bounce_stiffness,liquid_bounce_damping,pure_black").eq("id",id).maybeSingle().then(({data,error})=>{if(!active)return;if(error){console.warn("Could not load cloud customization",error);return;}if(data){setLiquidState(prev=>sanitize({...prev,density:data.liquid_density??prev.density,transparency:data.liquid_transparency??prev.transparency,clearness:data.liquid_clearness??prev.clearness,gel:data.liquid_gel??prev.gel,bounceStiffness:data.liquid_bounce_stiffness??prev.bounceStiffness,bounceDamping:data.liquid_bounce_damping??prev.bounceDamping}));if(data.theme==="light"||data.theme==="dark")setThemeState(data.theme);if(typeof data.display_name==="string")setDisplayNameState(data.display_name);if(typeof data.pure_black==="boolean")setPureBlackState(data.pure_black);}setProfileReady(true);});};void supabase.auth.getUser().then(({data})=>load(data.user?.id??null));const{data:listener}=supabase.auth.onAuthStateChange((_event,session)=>load(session?.user?.id??null));return()=>{active=false;listener.subscription.unsubscribe();};},[]);
  useEffect(()=>{if(!userId)return;try{localStorage.setItem(scoped(LEGACY_KEYS.liquid,userId),JSON.stringify(liquid));}catch{}const root=document.documentElement;const transparency=liquid.transparency/100;root.style.setProperty("--liquid-density",`${liquid.density}px`);root.style.setProperty("--liquid-transparency",`${transparency}`);root.style.setProperty("--liquid-glass-alpha",`${transparency}`);root.style.setProperty("--liquid-glass-dark-alpha",`${transparency*0.16}`);root.style.setProperty("--liquid-veil-alpha",`${transparency*0.36}`);const darkVeilAlpha=transparency<=0.45?0.0775+0.45*transparency:0.46-0.4*transparency;root.style.setProperty("--liquid-dark-veil-alpha",`${darkVeilAlpha}`);root.style.setProperty("--liquid-clearness",`${liquid.clearness}`);root.style.setProperty("--liquid-gel",`${liquid.gel}`);root.style.setProperty("--liquid-bounce",`${liquid.bounceStiffness}`);root.style.setProperty("--liquid-bounce-damping",`${liquid.bounceDamping}`);root.style.setProperty("--liquid-saturation",`${liquid.saturation}%`);root.style.setProperty("--liquid-sheen",`${liquid.sheen}`);root.style.setProperty("--liquid-refraction",`${liquid.refraction}`);},[liquid,userId]);
  useEffect(()=>{if(!userId||!profileReady)return;try{localStorage.setItem(scoped(LEGACY_KEYS.theme,userId),theme);}catch{}document.documentElement.classList.toggle("dark",theme==="dark");document.documentElement.style.colorScheme=theme;const timer=window.setTimeout(()=>{void supabase.from("profiles").upsert({id:userId,theme});},150);return()=>window.clearTimeout(timer);},[theme,userId,profileReady]);
  useEffect(()=>{if(!userId||!profileReady)return;try{localStorage.setItem(scoped(LEGACY_KEYS.displayName,userId),displayName);}catch{}const timer=window.setTimeout(()=>{void supabase.from("profiles").upsert({id:userId,display_name:displayName||null});},250);return()=>window.clearTimeout(timer);},[displayName,userId,profileReady]);
  useEffect(()=>{if(!userId||!profileReady)return;try{localStorage.setItem(scoped(LEGACY_KEYS.pureBlack,userId),pureBlack?"1":"0");}catch{}document.documentElement.classList.toggle("pure-black",pureBlack);const timer=window.setTimeout(()=>{void supabase.from("profiles").upsert({id:userId,pure_black:pureBlack});},150);return()=>window.clearTimeout(timer);},[pureBlack,userId,profileReady]);
  useEffect(()=>{if(!userId||!profileReady)return;const timer=window.setTimeout(()=>{void supabase.from("profiles").upsert({id:userId,liquid_density:liquid.density,liquid_transparency:liquid.transparency,liquid_clearness:liquid.clearness,liquid_gel:liquid.gel,liquid_bounce_stiffness:liquid.bounceStiffness,liquid_bounce_damping:liquid.bounceDamping});},400);return()=>window.clearTimeout(timer);},[liquid,userId,profileReady]);
  const value=useMemo<Ctx>(()=>({liquid,setLiquid:patch=>setLiquidState(prev=>sanitize({...prev,...patch})),reset:()=>setLiquidState(LIQUID_DEFAULTS),theme,setTheme:setThemeState,toggleTheme:()=>setThemeState(p=>p==="dark"?"light":"dark"),displayName,setDisplayName:name=>setDisplayNameState(name.trim().slice(0,40)),pureBlack,setPureBlack:v=>{if(v)setThemeState("dark");setPureBlackState(v);}}),[liquid,theme,displayName,pureBlack]);
  return <CustomizationContext.Provider value={value}>{children}</CustomizationContext.Provider>;
}
export function useCustomization(){const ctx=useContext(CustomizationContext);if(!ctx)throw new Error("useCustomization must be used inside CustomizationProvider");return ctx;}
