export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]
export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.15" }
  public: { Tables: {
    collections: { Row: { course_id:string; created_at:string; id:string; name:string; updated_at:string; user_id:string }; Insert: { course_id:string; created_at?:string; id?:string; name:string; updated_at?:string; user_id?:string }; Update: { course_id?:string; created_at?:string; id?:string; name?:string; updated_at?:string; user_id?:string }; Relationships: [] }
    courses: { Row: { color:string; created_at:string; description:string; id:string; name:string; updated_at:string; user_id:string }; Insert: { color?:string; created_at?:string; description?:string; id?:string; name:string; updated_at?:string; user_id:string }; Update: { color?:string; description?:string; id?:string; name?:string; updated_at?:string; user_id?:string }; Relationships: [] }
    notes: { Row: { body:string; collection_id:string|null; course_id:string; created_at:string; favorite:boolean; id:string; revision:number; source_id:string|null; title:string; updated_at:string; user_id:string }; Insert: { body?:string; collection_id?:string|null; course_id:string; created_at?:string; favorite?:boolean; id?:string; revision?:number; source_id?:string|null; title?:string; updated_at?:string; user_id:string }; Update: { body?:string; collection_id?:string|null; course_id?:string; favorite?:boolean; id?:string; revision?:number; source_id?:string|null; title?:string; updated_at?:string; user_id?:string }; Relationships: [] }
    profiles: { Row: { created_at:string; display_name:string|null; id:string; liquid_bounce_damping:number; liquid_bounce_stiffness:number; liquid_clearness:number; liquid_density:number; liquid_enabled:boolean; liquid_gel:number; liquid_realism:number; liquid_sharpness:number; liquid_transparency:number; theme:string; updated_at:string; pure_black:boolean; performance_mode:string }; Insert: { created_at?:string; display_name?:string|null; id:string; liquid_bounce_damping?:number; liquid_bounce_stiffness?:number; liquid_clearness?:number; liquid_density?:number; liquid_enabled?:boolean; liquid_gel?:number; liquid_realism?:number; liquid_sharpness?:number; liquid_transparency?:number; theme?:string; updated_at?:string; pure_black?:boolean; performance_mode?:string }; Update: { created_at?:string; display_name?:string|null; id?:string; liquid_bounce_damping?:number; liquid_bounce_stiffness?:number; liquid_clearness?:number; liquid_density?:number; liquid_enabled?:boolean; liquid_gel?:number; liquid_realism?:number; liquid_sharpness?:number; liquid_transparency?:number; theme?:string; updated_at?:string; pure_black?:boolean; performance_mode?:string }; Relationships: [] }
  }; Views: { [_ in never]: never }; Functions: {
    restore_course_batch: { Args: { p_course_id:string; p_collections:Json; p_notes:Json }; Returns:Json }
  }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never } }
}
type DatabaseWithoutInternals = Omit<Database,"__InternalSupabase">; type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database,"public">];
export type Tables<T extends keyof DefaultSchema["Tables"]> = DefaultSchema["Tables"][T] extends {Row:infer R}?R:never;
export type TablesInsert<T extends keyof DefaultSchema["Tables"]> = DefaultSchema["Tables"][T] extends {Insert:infer I}?I:never;
export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> = DefaultSchema["Tables"][T] extends {Update:infer U}?U:never;
export type Enums<T extends keyof DefaultSchema["Enums"]> = DefaultSchema["Enums"][T];
export type CompositeTypes<T extends keyof DefaultSchema["CompositeTypes"]> = DefaultSchema["CompositeTypes"][T];
export const Constants={public:{Enums:{}}} as const;
